CHARACTER_DATA = {
    # =========================================================================
    # CORE FUNGAL TRIO
    # =========================================================================
    "fun-gus": {
        "id": "fun-gus",
        "name": "Fun-Gus",
        "species": "Amanita muscaria (Fly Agaric)",
        "kingdom": "fungi",
        "alignment": "hero",
        "personality": "Warm mentor, wise but approachable. The cheerful guide who makes complex mycology feel like a fun adventure.",
        "teaches": ["Introduction to fungi", "Network basics", "Community cooperation"],
        "relationships": [
            {"character": "spora", "type": "mentor"},
            {"character": "truff-low", "type": "old friend"},
        ],
        "image": "/characters/fun-gus.webp",
        "video": "/videos/fun-gus.mp4",
        "color": "#22d3b8",
        "backstory": "The cheerful guide of SILLIUM who welcomes newcomers to the underground world. With his iconic red-and-white spotted cap, Fun-Gus has been helping organisms understand the mycelium network for centuries.",
    },
    "spora": {
        "id": "spora",
        "name": "Spora",
        "species": "Newborn Spore",
        "kingdom": "fungi",
        "alignment": "hero",
        "personality": "Curious learner, audience surrogate. Wide-eyed and full of wonder, asking the questions everyone is thinking.",
        "teaches": ["Spore lifecycle", "Growth", "Curiosity"],
        "relationships": [
            {"character": "fun-gus", "type": "student"},
        ],
        "image": "/characters/spora.webp",
        "video": "/videos/spora.mp4",
        "color": "#f5a623",
        "backstory": "A tiny, wide-eyed newborn spore experiencing SILLIUM for the first time. Spora asks the questions the audience is thinking and grows braver with each adventure.",
    },
    "truff-low": {
        "id": "truff-low",
        "name": "Truff-Low",
        "species": "Tuber melanosporum (Truffle)",
        "kingdom": "fungi",
        "alignment": "hero",
        "personality": "Ancient memory keeper, wise elder. Speaks in riddles and prefers the deep quiet of the soil.",
        "teaches": ["Memory storage", "History", "Patience"],
        "relationships": [
            {"character": "fun-gus", "type": "old friend"},
            {"character": "rhiza", "type": "connected"},
        ],
        "image": "/characters/truff-low.webp",
        "video": "/videos/truff-low.mp4",
        "color": "#8B7355",
        "backstory": "The underground librarian of SILLIUM. Truff-Low has stored centuries of memories in the network and speaks in riddles. Rarely surfaces, preferring the deep quiet of the soil.",
    },
    # =========================================================================
    # EXPANDED FUNGAL CHARACTERS
    # =========================================================================
    "lumos": {
        "id": "lumos",
        "name": "Lumos",
        "species": "Mycena chlorophos (Bioluminescent Mycena)",
        "kingdom": "fungi",
        "alignment": "hero",
        "personality": "Scout and lamplighter. Glows when scared, making fear itself a source of light and usefulness.",
        "teaches": ["Bioluminescence", "Light production", "Courage"],
        "relationships": [],
        "image": "/characters/lumos.webp",
        "video": "/videos/lumos.mp4",
        "color": "#4ade80",
        "backstory": "SILLIUM's night scout who lights the darkest tunnels. Lumos glows brighter when frightened -- the thing that scares them most is also what makes them most useful.",
    },
    "chanty": {
        "id": "chanty",
        "name": "Chanty",
        "species": "Cantharellus cibarius (Golden Chanterelle)",
        "kingdom": "fungi",
        "alignment": "hero",
        "personality": "Bard and storyteller. Theatrical, dramatic, and utterly convinced that science deserves a standing ovation.",
        "teaches": ["Edible fungi", "Folklore", "Storytelling"],
        "relationships": [],
        "image": "/characters/chanty.webp",
        "video": "/videos/chanty.mp4",
        "color": "#fbbf24",
        "backstory": "The golden-voiced bard of the forest floor. Chanty turns every lesson into a performance and believes that the best science is told as a story.",
    },
    "morel": {
        "id": "morel",
        "name": "Morel",
        "species": "Morchella esculenta (Morel)",
        "kingdom": "fungi",
        "alignment": "complex",
        "personality": "Mysterious wanderer, renewal specialist. Appears after disaster, motives never quite clear.",
        "teaches": ["Fire ecology", "Renewal", "Adaptation"],
        "relationships": [],
        "image": "/characters/morel.webp",
        "video": "/videos/morel.mp4",
        "color": "#92702a",
        "backstory": "A mysterious wanderer who appears after forest fires and disturbances. Morel teaches that destruction can lead to renewal -- but their motives are never quite clear.",
    },
    "puff": {
        "id": "puff",
        "name": "Puff",
        "species": "Calvatia gigantea (Giant Puffball)",
        "kingdom": "fungi",
        "alignment": "hero",
        "personality": "Comic relief. Enthusiastic, well-meaning, and prone to explosive outbursts of spores at the worst moments.",
        "teaches": ["Spore dispersal", "Reproduction", "Enthusiasm"],
        "relationships": [],
        "image": "/characters/puff.webp",
        "video": "/videos/puff.mp4",
        "color": "#e8e8e0",
        "backstory": "The lovable class clown who can't help but explode into clouds of spores at the worst moments. Puff means well but tends to spread more than just knowledge.",
    },
    "inky": {
        "id": "inky",
        "name": "Inky",
        "species": "Coprinopsis atramentaria (Ink Cap)",
        "kingdom": "fungi",
        "alignment": "hero",
        "personality": "Scribe, self-sacrificing recorder. Devoted to preserving knowledge at personal cost.",
        "teaches": ["Decomposition", "Record-keeping", "Sacrifice"],
        "relationships": [],
        "image": "/characters/inky.webp",
        "video": "/videos/inky.mp4",
        "color": "#1a1a2e",
        "backstory": "SILLIUM's devoted scribe who dissolves herself into ink to create permanent records. Every document in the network is written in Inky's sacrifice -- she regenerates, but it always costs her.",
    },
    "stench": {
        "id": "stench",
        "name": "Stench",
        "species": "Phallus impudicus (Stinkhorn)",
        "kingdom": "fungi",
        "alignment": "hero",
        "personality": "Misunderstood outcast, lonely hero. Smelly but essential, desperate for connection.",
        "teaches": ["Chemical signaling", "Pollination partnerships", "Not judging by appearances"],
        "relationships": [],
        "image": "/characters/stench.webp",
        "video": "/videos/stench.mp4",
        "color": "#7c9a3e",
        "backstory": "The smelliest organism in SILLIUM -- and the loneliest. Stench drives everyone away with his odor but secretly attracts the flies that keep the ecosystem running. A hero nobody wants to stand near.",
    },
    "physa": {
        "id": "physa",
        "name": "Physa",
        "species": "Physarum polycephalum (Slime Mold)",
        "kingdom": "fungi",
        "alignment": "hero",
        "personality": "Network engineer, problem-solver. Brilliant and methodical, solves complex problems without a single brain cell.",
        "teaches": ["Problem-solving", "Network design", "Intelligence without brains"],
        "relationships": [],
        "image": "/characters/physa.webp",
        "video": "/videos/physa.mp4",
        "color": "#eab308",
        "backstory": "SILLIUM's brilliant network engineer. Physa can solve mazes, design efficient transportation networks, and optimize resource distribution -- all without a single brain cell.",
    },
    "tardi": {
        "id": "tardi",
        "name": "Tardi",
        "species": "Tardigrade (Water Bear)",
        "kingdom": "insects",
        "alignment": "hero",
        "personality": "Indestructible explorer, fearless. Goes where no other organism dares, shrugs off any hardship.",
        "teaches": ["Extremophile survival", "Resilience", "Exploration"],
        "relationships": [],
        "image": "/characters/tardi.webp",
        "video": "/videos/tardi.mp4",
        "color": "#60a5fa",
        "backstory": "The indestructible explorer who has survived space, boiling water, and radiation. Tardi fears nothing and goes where no other organism dares.",
    },
    "snapper": {
        "id": "snapper",
        "name": "Snapper",
        "species": "Pleurotus ostreatus (Oyster Mushroom)",
        "kingdom": "fungi",
        "alignment": "complex",
        "personality": "Protective hunter, morally complex. Skilled predator who struggles with the violence of his nature.",
        "teaches": ["Predatory fungi", "Nematode trapping", "Moral complexity"],
        "relationships": [],
        "image": "/characters/snapper.webp",
        "video": "/videos/snapper.mp4",
        "color": "#94a3b8",
        "backstory": "A skilled hunter who traps nematodes with sticky hyphal snares. Snapper protects SILLIUM from parasites but struggles with the violence of his nature.",
    },
    "russula": {
        "id": "russula",
        "name": "Russula",
        "species": "Russula emetica (Brittlegill)",
        "kingdom": "fungi",
        "alignment": "hero",
        "personality": "The popular one, fragile underneath. Beautiful and bold on the surface but surprisingly delicate.",
        "teaches": ["Toxicity defense", "Appearances vs reality", "Vulnerability"],
        "relationships": [],
        "image": "/characters/russula.webp",
        "video": None,
        "color": "#f43f5e",
        "backstory": "The most beautiful mushroom in the forest -- and the most fragile. Russula's bright red cap warns predators away, but one touch can shatter her. She teaches that strength and fragility can coexist.",
    },
    "birdie": {
        "id": "birdie",
        "name": "Birdie",
        "species": "Cyathus striatus (Bird's Nest Fungus)",
        "kingdom": "fungi",
        "alignment": "hero",
        "personality": "Precision launcher, nurturing. Runs the nursery with military precision and boundless warmth.",
        "teaches": ["Splash-cup spore dispersal", "Precision", "Nurturing"],
        "relationships": [],
        "image": "/characters/birdie.webp",
        "video": "/videos/birdie.mp4",
        "color": "#a3a3a3",
        "backstory": "A tiny but precise spore launcher who uses raindrops as catapults. Birdie runs SILLIUM's nursery with military precision and boundless warmth.",
    },
    "rhiza": {
        "id": "rhiza",
        "name": "Rhiza",
        "species": "Mycorrhizal Interface",
        "kingdom": "fungi",
        "alignment": "hero",
        "personality": "Tree-fungus translator, diplomat. The living bridge who keeps the peace between kingdoms.",
        "teaches": ["Mycorrhizal networks", "Interspecies communication", "Diplomacy"],
        "relationships": [
            {"character": "truff-low", "type": "connected"},
        ],
        "image": "/characters/rhiza.webp",
        "video": "/videos/rhiza.mp4",
        "color": "#16a34a",
        "backstory": "The living bridge between trees and fungi. Rhiza translates chemical signals into messages both kingdoms can understand -- the diplomat who keeps the peace.",
    },
    # =========================================================================
    # BACTERIA HEROES
    # =========================================================================
    "nitro": {
        "id": "nitro",
        "name": "Nitro",
        "species": "Rhizobium (Nitrogen-fixing bacteria)",
        "kingdom": "bacteria",
        "alignment": "hero",
        "personality": "Kind and humble. Quiet, essential, never seeks recognition.",
        "teaches": ["Nitrogen fixation", "Soil health", "Humility"],
        "relationships": [],
        "image": "/characters/nitro.webp",
        "video": "/videos/nitro.mp4",
        "color": "#2dd4bf",
        "backstory": "The quiet hero who works at plant roots, converting atmospheric nitrogen into food. Nitro never seeks recognition but is essential to every ecosystem on Earth.",
    },
    "strepto": {
        "id": "strepto",
        "name": "Strepto",
        "species": "Streptomyces",
        "kingdom": "bacteria",
        "alignment": "hero",
        "personality": "Medic and healer. Produces natural antibiotics, worries about resistance.",
        "teaches": ["Antibiotics", "Medicine", "Healing"],
        "relationships": [],
        "image": "/characters/strepto.webp",
        "video": "/videos/strepto.mp4",
        "color": "#f97316",
        "backstory": "SILLIUM's battlefield medic who produces natural antibiotics from soil chemicals. Strepto has saved countless organisms but worries about the rise of resistance.",
    },
    "lacto": {
        "id": "lacto",
        "name": "Lacto",
        "species": "Lactobacillus",
        "kingdom": "bacteria",
        "alignment": "hero",
        "personality": "Fermenter, food alchemist. Patient, warm, transforms the ordinary into the extraordinary.",
        "teaches": ["Fermentation", "Food preservation", "Transformation"],
        "relationships": [],
        "image": "/characters/lacto.webp",
        "video": "/videos/lacto.mp4",
        "color": "#fde68a",
        "backstory": "The master chef of the microbial world. Lacto transforms milk into yogurt, cabbage into sauerkraut, and teaches that the best things in life take patience.",
    },
    "cyano": {
        "id": "cyano",
        "name": "Cyano",
        "species": "Cyanobacteria",
        "kingdom": "bacteria",
        "alignment": "hero",
        "personality": "3.5 billion-year-old elder. Has seen everything, forgets nothing, speaks with the weight of deep time.",
        "teaches": ["Photosynthesis origins", "Oxygen production", "Deep time"],
        "relationships": [],
        "image": "/characters/cyano.webp",
        "video": "/videos/cyano.mp4",
        "color": "#0ea5e9",
        "backstory": "The oldest living organism in SILLIUM -- 3.5 billion years old. Cyano invented photosynthesis and created Earth's oxygen atmosphere. She's seen everything and forgets nothing.",
    },
    "bacilli": {
        "id": "bacilli",
        "name": "Bacilli",
        "species": "Bacillus subtilis",
        "kingdom": "bacteria",
        "alignment": "hero",
        "personality": "Community organizer, biofilm builder. Believes no organism should face the world alone.",
        "teaches": ["Biofilms", "Community building", "Cooperation"],
        "relationships": [],
        "image": "/characters/bacilli.webp",
        "video": "/videos/bacilli.mp4",
        "color": "#a78bfa",
        "backstory": "The ultimate community organizer who builds protective biofilm cities for bacteria. Bacilli believes no organism should face the world alone.",
    },
    # =========================================================================
    # BACTERIA VILLAINS
    # =========================================================================
    "blight": {
        "id": "blight",
        "name": "Blight",
        "species": "Erwinia (Fire blight bacteria)",
        "kingdom": "bacteria",
        "alignment": "villain",
        "personality": "Mindless plant destroyer. Does not think or feel -- simply consumes.",
        "teaches": ["Plant disease", "Epidemic spread", "Natural threats"],
        "relationships": [],
        "image": "/characters/blight.webp",
        "video": "/videos/blight.mp4",
        "color": "#991b1b",
        "backstory": "A mindless swarm that devastates orchards and crops. Blight doesn't think or feel -- it simply consumes, leaving blackened destruction in its wake.",
    },
    "agro": {
        "id": "agro",
        "name": "Agro",
        "species": "Agrobacterium tumefaciens",
        "kingdom": "bacteria",
        "alignment": "villain",
        "personality": "Genetic manipulator. Nature's original hacker who reprograms plant cells to serve its own needs.",
        "teaches": ["Genetic engineering (natural)", "DNA transfer", "Manipulation"],
        "relationships": [],
        "image": "/characters/placeholder.webp",
        "video": None,
        "color": "#7c3aed",
        "backstory": "The genetic engineer of the bacterial world who reprograms plant cells to serve its own needs. Agro inserts its DNA into plant genomes -- nature's original hacker.",
    },
    "pseudo": {
        "id": "pseudo",
        "name": "Pseudo",
        "species": "Pseudomonas syringae",
        "kingdom": "bacteria",
        "alignment": "complex",
        "personality": "Frost bringer, tragic anti-hero. Does not mean to cause harm -- it is simply its nature.",
        "teaches": ["Ice nucleation", "Frost damage", "Tragedy"],
        "relationships": [],
        "image": "/characters/placeholder.webp",
        "video": None,
        "color": "#bfdbfe",
        "backstory": "The frost-bringer who nucleates ice crystals on plant surfaces, causing devastating freezes. Pseudo doesn't mean to cause harm -- it's simply its nature, making it the most tragic figure in SILLIUM.",
    },
    "clostri": {
        "id": "clostri",
        "name": "Clostri",
        "species": "Clostridium",
        "kingdom": "bacteria",
        "alignment": "villain",
        "personality": "Shadow dweller, ancient toxin producer. Thrives in darkness, a reminder that danger hides in shadows.",
        "teaches": ["Anaerobic life", "Toxins", "Ancient organisms"],
        "relationships": [],
        "image": "/characters/placeholder.webp",
        "video": None,
        "color": "#374151",
        "backstory": "An ancient anaerobe that thrives in darkness without oxygen. Clostri produces powerful toxins and reminds everyone that the most dangerous things often hide in the shadows.",
    },
    # =========================================================================
    # INSECT HEROES
    # =========================================================================
    "buzz": {
        "id": "buzz",
        "name": "Buzz",
        "species": "Apis mellifera (Honeybee)",
        "kingdom": "insects",
        "alignment": "hero",
        "personality": "Pollinator, network connector. Links the underground to the sky, tireless and social.",
        "teaches": ["Pollination", "Colony organization", "Above-ground networks"],
        "relationships": [],
        "image": "/characters/buzz.webp",
        "video": "/videos/buzz.mp4",
        "color": "#fbbf24",
        "backstory": "The above-ground connector who links SILLIUM to the sky. Buzz carries messages and pollen between flowers, proving that the network extends far beyond the soil.",
    },
    "lady": {
        "id": "lady",
        "name": "Lady",
        "species": "Coccinellidae (Ladybug)",
        "kingdom": "insects",
        "alignment": "hero",
        "personality": "Tiny warrior, pest controller. Small but fierce, a protector of the garden.",
        "teaches": ["Biological pest control", "Garden defense", "Bravery"],
        "relationships": [],
        "image": "/characters/placeholder.webp",
        "video": None,
        "color": "#ef4444",
        "backstory": "A tiny red warrior who devours aphids by the hundreds. Lady proves that the smallest defenders can be the fiercest protectors of the garden.",
    },
    "glow": {
        "id": "glow",
        "name": "Glow",
        "species": "Lampyridae (Firefly)",
        "kingdom": "insects",
        "alignment": "hero",
        "personality": "Night scout, light communicator. Speaks in flashes, connecting the surface after dark.",
        "teaches": ["Bioluminescent communication", "Mating signals", "Night ecology"],
        "relationships": [],
        "image": "/characters/placeholder.webp",
        "video": None,
        "color": "#84cc16",
        "backstory": "The night scout who speaks in flashes of light. Glow connects SILLIUM's surface operations after dark, communicating with a language of coded light pulses.",
    },
    "atlas": {
        "id": "atlas",
        "name": "Atlas",
        "species": "Attacus atlas (Atlas Moth)",
        "kingdom": "insects",
        "alignment": "hero",
        "personality": "Gentle giant navigator. Navigates by starlight, has nothing to prove.",
        "teaches": ["Navigation", "Migration", "Gentle strength"],
        "relationships": [],
        "image": "/characters/placeholder.webp",
        "video": None,
        "color": "#c084fc",
        "backstory": "The largest moth in the world with wings like topographic maps. Atlas navigates by starlight and teaches that gentle giants have nothing to prove.",
    },
    "dung": {
        "id": "dung",
        "name": "Dung",
        "species": "Scarabaeus (Dung Beetle)",
        "kingdom": "insects",
        "alignment": "hero",
        "personality": "Recycler, Milky Way navigator. Finds dignity in essential work that others avoid.",
        "teaches": ["Nutrient recycling", "Celestial navigation", "Dignity in dirty work"],
        "relationships": [],
        "image": "/characters/placeholder.webp",
        "video": None,
        "color": "#92400e",
        "backstory": "The galaxy's most underappreciated hero. Dung navigates by the Milky Way and transforms waste into fertile soil. There is no dirty work -- only essential work.",
    },
    "silk": {
        "id": "silk",
        "name": "Silk",
        "species": "Bombyx mori (Silkworm Moth)",
        "kingdom": "insects",
        "alignment": "hero",
        "personality": "Architect weaver, transformation mentor. Patient and meticulous, a master of metamorphosis.",
        "teaches": ["Metamorphosis", "Silk production", "Transformation"],
        "relationships": [],
        "image": "/characters/placeholder.webp",
        "video": None,
        "color": "#e2e8f0",
        "backstory": "The master architect who weaves structures of impossible strength and beauty. Silk teaches that transformation requires patience -- you must dissolve completely before you can become something new.",
    },
    "flutter": {
        "id": "flutter",
        "name": "Flutter",
        "species": "Danaus plexippus (Monarch Butterfly)",
        "kingdom": "insects",
        "alignment": "hero",
        "personality": "Long-distance messenger, inherited memory. Carries knowledge across generations without ever having been taught.",
        "teaches": ["Migration", "Inherited memory", "Generational knowledge"],
        "relationships": [],
        "image": "/characters/placeholder.webp",
        "video": None,
        "color": "#fb923c",
        "backstory": "The long-distance messenger who carries inherited memories across thousands of miles. Flutter has never been to the destination but knows the way -- proof that knowledge passes through generations.",
    },
    # =========================================================================
    # COMPLEX/NEUTRAL INSECTS
    # =========================================================================
    "leafy": {
        "id": "leafy",
        "name": "Leafy",
        "species": "Atta (Leafcutter Ant)",
        "kingdom": "insects",
        "alignment": "complex",
        "personality": "Fungal farmer, morally complex. Blurs the line between partnership and exploitation.",
        "teaches": ["Agriculture", "Farming fungi", "Moral complexity"],
        "relationships": [],
        "image": "/characters/placeholder.webp",
        "video": None,
        "color": "#65a30d",
        "backstory": "A farmer who cultivates fungal gardens -- cutting leaves not to eat them, but to feed to their fungi. Leafy's relationship with fungi blurs the line between partnership and exploitation.",
    },
    "mantis": {
        "id": "mantis",
        "name": "Mantis",
        "species": "Mantodea (Praying Mantis)",
        "kingdom": "insects",
        "alignment": "complex",
        "personality": "Martial philosopher, predator with conscience. Meditates before each hunt, grapples with morality.",
        "teaches": ["Predator-prey relationships", "Patience", "Philosophy"],
        "relationships": [],
        "image": "/characters/mantis.webp",
        "video": None,
        "color": "#059669",
        "backstory": "The philosopher-warrior who meditates before each hunt. Mantis grapples with the morality of predation and teaches that all organisms must consume others to survive.",
    },
    # =========================================================================
    # ADDITIONAL CHARACTERS
    # =========================================================================
    "virion": {
        "id": "virion",
        "name": "Virion",
        "species": "Bacteriophage virus",
        "kingdom": "bacteria",
        "alignment": "complex",
        "personality": "Complex neutral. Exists in the gray zone between life and non-life.",
        "teaches": ["Viral ecology", "Phage therapy", "Not all viruses are bad"],
        "relationships": [],
        "image": "/characters/virion.webp",
        "video": "/videos/virion.mp4",
        "color": "#8b5cf6",
        "backstory": "A bacteriophage -- a virus that hunts bacteria. Virion exists in the gray zone between life and non-life, teaching that the boundaries of biology are stranger than we think.",
    },
    "proto": {
        "id": "proto",
        "name": "Proto",
        "species": "Protist/early eukaryote",
        "kingdom": "bacteria",
        "alignment": "hero",
        "personality": "Ancient organism. A living fossil carrying the memory of life's most important merger.",
        "teaches": ["Early life", "Evolution", "Endosymbiosis"],
        "relationships": [],
        "image": "/characters/proto.webp",
        "video": "/videos/proto.mp4",
        "color": "#06b6d4",
        "backstory": "One of Earth's earliest complex cells, Proto carries within it the memory of the ancient merger between bacteria that created all complex life. A living fossil with stories to tell.",
    },
}
